version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=database
    ports:
      - "3330:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
